/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AppPackage;

import java.awt.Cursor;
import java.awt.Image;
import java.awt.Point;
import java.awt.Toolkit;

/**
 *
 * @author Zach
 */
public class adminGUI extends javax.swing.JFrame {

    /**
     * Creates new form StartGUI
     */
    int xMouse;
    int yMouse;
    public adminGUI() {
        initComponents();
        CustomCursor();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        adminTitle = new javax.swing.JLabel();
        checkUser = new javax.swing.JButton();
        registerTitle = new javax.swing.JLabel();
        closeB = new javax.swing.JLabel();
        miniB = new javax.swing.JLabel();
        background = new javax.swing.JLabel();
        frameDrag = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("DCPlanner");
        setBackground(new java.awt.Color(0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        setForeground(new java.awt.Color(105, 105, 105));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        adminTitle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppPackage/adminTitle.png"))); // NOI18N
        getContentPane().add(adminTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 440, -1, -1));

        checkUser.setText("Check Users");
        checkUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                checkUserMouseReleased(evt);
            }
        });
        checkUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkUserActionPerformed(evt);
            }
        });
        getContentPane().add(checkUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, 130, 50));

        registerTitle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/adminTitle.png"))); // NOI18N
        getContentPane().add(registerTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 430, -1, -1));

        closeB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppPackage/close.png"))); // NOI18N
        closeB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        closeB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeBMouseClicked(evt);
            }
        });
        getContentPane().add(closeB, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 20, 50, -1));

        miniB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppPackage/mini.png"))); // NOI18N
        miniB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        miniB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                miniBMouseClicked(evt);
            }
        });
        getContentPane().add(miniB, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 20, -1, -1));

        background.setFont(new java.awt.Font("Segoe UI Light", 0, 11)); // NOI18N
        background.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppPackage/GUI.png"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, -1));

        frameDrag.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                frameDragMouseDragged(evt);
            }
        });
        frameDrag.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                frameDragMousePressed(evt);
            }
        });
        getContentPane().add(frameDrag, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -6, 820, 30));

        setSize(new java.awt.Dimension(800, 598));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    public void CustomCursor(){
        Toolkit toolkit = Toolkit.getDefaultToolkit();
        Image img = toolkit.getImage("Cursor.png");
        Point point = new Point(0,0);
        Cursor cursor = toolkit.createCustomCursor(img, point, "Cursor");
        
        setCursor(cursor);
    }
    private void miniBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_miniBMouseClicked
        this.setState(adminGUI.ICONIFIED);
    }//GEN-LAST:event_miniBMouseClicked

    private void closeBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeBMouseClicked
        System.exit(0);
    }//GEN-LAST:event_closeBMouseClicked

    private void frameDragMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_frameDragMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_frameDragMouseDragged

    private void frameDragMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_frameDragMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_frameDragMousePressed

    private void checkUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkUserActionPerformed

    }//GEN-LAST:event_checkUserActionPerformed

    private void checkUserMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkUserMouseReleased

    }//GEN-LAST:event_checkUserMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adminGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adminGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adminGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adminGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    Thread.sleep(5000);
                }
                catch(Exception e){
                    
                }
                new adminGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel adminTitle;
    private javax.swing.JLabel background;
    private javax.swing.JButton checkUser;
    private javax.swing.JLabel closeB;
    private javax.swing.JLabel frameDrag;
    private javax.swing.JLabel miniB;
    private javax.swing.JLabel registerTitle;
    // End of variables declaration//GEN-END:variables
}
