/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AppPackage;

import java.awt.Cursor;
import java.awt.Image;
import java.awt.Point;
import java.awt.Toolkit;

/**
 *
 * @author Zach
 */
public class userGUI extends javax.swing.JFrame {

    /**
     * Creates new form StartGUI
     */
    int xMouse;
    int yMouse;
    public userGUI() {
        initComponents();
        CustomCursor();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        submitButton = new javax.swing.JLabel();
        brokeTitle = new javax.swing.JTextField();
        brokeSeparator = new javax.swing.JLabel();
        Parks = new javax.swing.JCheckBox();
        freeCheck = new javax.swing.JCheckBox();
        histCheck = new javax.swing.JCheckBox();
        theaterCheck = new javax.swing.JCheckBox();
        monuCheck = new javax.swing.JCheckBox();
        museumsCheck = new javax.swing.JCheckBox();
        collegeCheck = new javax.swing.JCheckBox();
        whatSeparator = new javax.swing.JLabel();
        whatTitle = new javax.swing.JTextField();
        endTime = new javax.swing.JComboBox();
        startTime = new javax.swing.JComboBox();
        to = new javax.swing.JTextField();
        from = new javax.swing.JTextField();
        timeSeparator = new javax.swing.JLabel();
        timeTitle = new javax.swing.JTextField();
        miniB = new javax.swing.JLabel();
        closeB = new javax.swing.JLabel();
        planGenTitle = new javax.swing.JLabel();
        userTitle = new javax.swing.JLabel();
        registerTitle = new javax.swing.JLabel();
        background = new javax.swing.JLabel();
        frameDrag = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("DCPlanner");
        setBackground(new java.awt.Color(0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        setForeground(new java.awt.Color(105, 105, 105));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        submitButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppPackage/submitButton.png"))); // NOI18N
        submitButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                submitButtonMouseReleased(evt);
            }
        });
        getContentPane().add(submitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 410, -1, -1));

        brokeTitle.setEditable(false);
        brokeTitle.setBackground(new java.awt.Color(105, 105, 105));
        brokeTitle.setFont(new java.awt.Font("Raleway", 0, 36)); // NOI18N
        brokeTitle.setForeground(new java.awt.Color(255, 255, 255));
        brokeTitle.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        brokeTitle.setText("Broke college student?");
        brokeTitle.setToolTipText("");
        brokeTitle.setBorder(null);
        brokeTitle.setOpaque(false);
        brokeTitle.setSelectedTextColor(new java.awt.Color(0, 255, 255));
        brokeTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brokeTitleActionPerformed(evt);
            }
        });
        getContentPane().add(brokeTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 330, 390, 40));

        brokeSeparator.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppPackage/lineSeparator.png"))); // NOI18N
        getContentPane().add(brokeSeparator, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 350, 400, 20));

        Parks.setBackground(new java.awt.Color(105, 105, 105));
        Parks.setFont(new java.awt.Font("Raleway", 0, 24)); // NOI18N
        Parks.setForeground(new java.awt.Color(56, 195, 228));
        Parks.setText("Parks");
        Parks.setOpaque(false);
        getContentPane().add(Parks, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 290, -1, 40));

        freeCheck.setBackground(new java.awt.Color(105, 105, 105));
        freeCheck.setFont(new java.awt.Font("Raleway", 0, 24)); // NOI18N
        freeCheck.setForeground(new java.awt.Color(56, 195, 228));
        freeCheck.setText("Only show free things");
        freeCheck.setOpaque(false);
        freeCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                freeCheckActionPerformed(evt);
            }
        });
        getContentPane().add(freeCheck, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 370, -1, 40));

        histCheck.setBackground(new java.awt.Color(105, 105, 105));
        histCheck.setFont(new java.awt.Font("Raleway", 0, 24)); // NOI18N
        histCheck.setForeground(new java.awt.Color(56, 195, 228));
        histCheck.setText("Historical Sites");
        histCheck.setOpaque(false);
        getContentPane().add(histCheck, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, -1, 40));

        theaterCheck.setBackground(new java.awt.Color(105, 105, 105));
        theaterCheck.setFont(new java.awt.Font("Raleway", 0, 24)); // NOI18N
        theaterCheck.setForeground(new java.awt.Color(56, 195, 228));
        theaterCheck.setText("Theaters");
        theaterCheck.setOpaque(false);
        theaterCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                theaterCheckActionPerformed(evt);
            }
        });
        getContentPane().add(theaterCheck, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 290, -1, 40));

        monuCheck.setBackground(new java.awt.Color(105, 105, 105));
        monuCheck.setFont(new java.awt.Font("Raleway", 0, 24)); // NOI18N
        monuCheck.setForeground(new java.awt.Color(56, 195, 228));
        monuCheck.setText("Monuments");
        monuCheck.setOpaque(false);
        getContentPane().add(monuCheck, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 250, 160, 40));

        museumsCheck.setBackground(new java.awt.Color(105, 105, 105));
        museumsCheck.setFont(new java.awt.Font("Raleway", 0, 24)); // NOI18N
        museumsCheck.setForeground(new java.awt.Color(56, 195, 228));
        museumsCheck.setText("Museums");
        museumsCheck.setOpaque(false);
        getContentPane().add(museumsCheck, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, 140, 40));

        collegeCheck.setBackground(new java.awt.Color(105, 105, 105));
        collegeCheck.setFont(new java.awt.Font("Raleway", 0, 24)); // NOI18N
        collegeCheck.setForeground(new java.awt.Color(56, 195, 228));
        collegeCheck.setText("Colleges");
        collegeCheck.setOpaque(false);
        getContentPane().add(collegeCheck, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 250, 130, 40));

        whatSeparator.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppPackage/lineSeparator.png"))); // NOI18N
        getContentPane().add(whatSeparator, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, 400, 20));

        whatTitle.setEditable(false);
        whatTitle.setBackground(new java.awt.Color(105, 105, 105));
        whatTitle.setFont(new java.awt.Font("Raleway", 0, 36)); // NOI18N
        whatTitle.setForeground(new java.awt.Color(255, 255, 255));
        whatTitle.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        whatTitle.setText("What do you want to do?");
        whatTitle.setToolTipText("");
        whatTitle.setBorder(null);
        whatTitle.setOpaque(false);
        whatTitle.setSelectedTextColor(new java.awt.Color(0, 255, 255));
        whatTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                whatTitleActionPerformed(evt);
            }
        });
        getContentPane().add(whatTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, 440, 40));

        endTime.setBackground(new java.awt.Color(105, 105, 105));
        endTime.setFont(new java.awt.Font("Raleway", 1, 36)); // NOI18N
        endTime.setForeground(new java.awt.Color(56, 195, 228));
        endTime.setMaximumRowCount(4);
        endTime.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "12am", "1am", "2am", "3am", "4am", "5am", "6am", "7am", "8am", "9am", "10am", "11am", "12pm", "1pm", "2pm", "3pm", "4pm", "5pm", "6pm", "7pm", "8pm", "9pm", "10pm", "11pm" }));
        getContentPane().add(endTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 150, 130, 40));

        startTime.setBackground(new java.awt.Color(105, 105, 105));
        startTime.setFont(new java.awt.Font("Raleway", 1, 36)); // NOI18N
        startTime.setForeground(new java.awt.Color(56, 195, 228));
        startTime.setMaximumRowCount(4);
        startTime.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "12am", "1am", "2am", "3am", "4am", "5am", "6am", "7am", "8am", "9am", "10am", "11am", "12pm", "1pm", "2pm", "3pm", "4pm", "5pm", "6pm", "7pm", "8pm", "9pm", "10pm", "11pm" }));
        startTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startTimeActionPerformed(evt);
            }
        });
        getContentPane().add(startTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 150, 130, 40));

        to.setEditable(false);
        to.setBackground(new java.awt.Color(105, 105, 105));
        to.setFont(new java.awt.Font("Raleway", 2, 36)); // NOI18N
        to.setForeground(new java.awt.Color(255, 255, 255));
        to.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        to.setText("to");
        to.setToolTipText("");
        to.setBorder(null);
        to.setOpaque(false);
        to.setSelectedTextColor(new java.awt.Color(0, 255, 255));
        to.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toActionPerformed(evt);
            }
        });
        getContentPane().add(to, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 150, 40, -1));

        from.setEditable(false);
        from.setBackground(new java.awt.Color(105, 105, 105));
        from.setFont(new java.awt.Font("Raleway", 2, 36)); // NOI18N
        from.setForeground(new java.awt.Color(255, 255, 255));
        from.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        from.setText("I'm free from");
        from.setToolTipText("");
        from.setBorder(null);
        from.setOpaque(false);
        from.setSelectedTextColor(new java.awt.Color(0, 255, 255));
        from.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fromActionPerformed(evt);
            }
        });
        getContentPane().add(from, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 220, 40));

        timeSeparator.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppPackage/lineSeparator.png"))); // NOI18N
        getContentPane().add(timeSeparator, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, -1, 20));

        timeTitle.setEditable(false);
        timeTitle.setBackground(new java.awt.Color(105, 105, 105));
        timeTitle.setFont(new java.awt.Font("Raleway", 0, 36)); // NOI18N
        timeTitle.setForeground(new java.awt.Color(255, 255, 255));
        timeTitle.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        timeTitle.setText("When are you free?");
        timeTitle.setToolTipText("");
        timeTitle.setBorder(null);
        timeTitle.setOpaque(false);
        timeTitle.setSelectedTextColor(new java.awt.Color(0, 255, 255));
        timeTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timeTitleActionPerformed(evt);
            }
        });
        getContentPane().add(timeTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, 340, 40));

        miniB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppPackage/mini.png"))); // NOI18N
        miniB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        miniB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                miniBMouseClicked(evt);
            }
        });
        getContentPane().add(miniB, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 20, -1, -1));

        closeB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppPackage/close.png"))); // NOI18N
        closeB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        closeB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeBMouseClicked(evt);
            }
        });
        getContentPane().add(closeB, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 20, 50, -1));

        planGenTitle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppPackage/PlanGenTitle.png"))); // NOI18N
        getContentPane().add(planGenTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, -1, -1));

        userTitle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppPackage/UserTitle.png"))); // NOI18N
        getContentPane().add(userTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 440, -1, -1));

        registerTitle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/adminTitle.png"))); // NOI18N
        getContentPane().add(registerTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 430, -1, -1));

        background.setFont(new java.awt.Font("Segoe UI Light", 0, 11)); // NOI18N
        background.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppPackage/GUI.png"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, -1));

        frameDrag.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                frameDragMouseDragged(evt);
            }
        });
        frameDrag.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                frameDragMousePressed(evt);
            }
        });
        getContentPane().add(frameDrag, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -6, 820, 30));

        setSize(new java.awt.Dimension(800, 598));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    public void CustomCursor(){
        Toolkit toolkit = Toolkit.getDefaultToolkit();
        Image img = toolkit.getImage("Cursor.png");
        Point point = new Point(0,0);
        Cursor cursor = toolkit.createCustomCursor(img, point, "Cursor");
        
        setCursor(cursor);
    }
    private void frameDragMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_frameDragMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_frameDragMouseDragged

    private void frameDragMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_frameDragMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_frameDragMousePressed

    private void miniBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_miniBMouseClicked
        this.setState(adminGUI.ICONIFIED);
    }//GEN-LAST:event_miniBMouseClicked

    private void closeBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeBMouseClicked
        System.exit(0);
    }//GEN-LAST:event_closeBMouseClicked

    private void timeTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timeTitleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_timeTitleActionPerformed

    private void fromActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fromActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fromActionPerformed

    private void toActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_toActionPerformed

    private void startTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startTimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_startTimeActionPerformed

    private void whatTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_whatTitleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_whatTitleActionPerformed

    private void freeCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_freeCheckActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_freeCheckActionPerformed

    private void theaterCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_theaterCheckActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_theaterCheckActionPerformed

    private void brokeTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brokeTitleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_brokeTitleActionPerformed

    private void submitButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitButtonMouseReleased
        this.setVisible(false);
        StartGUI start = new StartGUI();
        start.setVisible(true);
        start.setLocation(this.getX(),this.getY());
    }//GEN-LAST:event_submitButtonMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(userGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(userGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(userGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(userGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    Thread.sleep(5000);
                }
                catch(Exception e){
                    
                }
                new userGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox Parks;
    private javax.swing.JLabel background;
    private javax.swing.JLabel brokeSeparator;
    private javax.swing.JTextField brokeTitle;
    private javax.swing.JLabel closeB;
    private javax.swing.JCheckBox collegeCheck;
    private javax.swing.JComboBox endTime;
    private javax.swing.JLabel frameDrag;
    private javax.swing.JCheckBox freeCheck;
    private javax.swing.JTextField from;
    private javax.swing.JCheckBox histCheck;
    private javax.swing.JLabel miniB;
    private javax.swing.JCheckBox monuCheck;
    private javax.swing.JCheckBox museumsCheck;
    private javax.swing.JLabel planGenTitle;
    private javax.swing.JLabel registerTitle;
    private javax.swing.JComboBox startTime;
    private javax.swing.JLabel submitButton;
    private javax.swing.JCheckBox theaterCheck;
    private javax.swing.JLabel timeSeparator;
    private javax.swing.JTextField timeTitle;
    private javax.swing.JTextField to;
    private javax.swing.JLabel userTitle;
    private javax.swing.JLabel whatSeparator;
    private javax.swing.JTextField whatTitle;
    // End of variables declaration//GEN-END:variables
}
